CREATE TABLE @ohdsiSchema.Radiology_Image (
  Image_ID                    NUMBER(19)          NOT NULL GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1,
  Radiology_Occurrence_ID     NUMBER(19)          NOT NULL,
  Person_ID                   NUMBER(19)          NOT NULL,
  Image_type                  VARCHAR(255)        NOT NULL,
  Radiology_Phase_Concept_ID  INTEGER             NOT NULL,
  Image_No                    INTEGER             NOT NULL,
  Phase_Total_No              INTEGER             NOT NULL,
  Image_Resolution_Rows       INTEGER             NOT NULL,
  Image_Resolution_Columns    INTEGER             NOT NULL,
  Image_Window_Level_Center   VARCHAR(255)        NULL,
  Image_Window_Level_Width    VARCHAR(255)        NULL,
  Image_Slice_Thickness       FLOAT               NULL,
  Image_filepath              VARCHAR(255)        NOT NULL
  CONSTRAINT RAD_IMG_PK PRIMARY KEY (Image_ID)
);
